parameters:
- name: azureServiceConnection
  type: string

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.6
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python Version: 3.6'
  
- script: |
    python -m pip install --upgrade pip
    pip install databricks-cli
  displayName: 'Setup Agent'
  
- task: AzureCLI@1
  displayName: Get Databricks token
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    scriptLocation: inlineScript
    inlineScript: |
      adbGlobalToken=$(az account get-access-token --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d --output json | jq -r .accessToken)
      echo "##vso[task.setvariable variable=DATABRICKS_TOKEN;isSecret=true]$adbGlobalToken"
    addSpnToEnvironment: true